FROM node:14 as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock  ./
RUN yarn install --frozen-lockfile --silent
RUN yarn global add react-scripts@3.4.1
COPY . ./
RUN yarn build

FROM nginx:1.22.1
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]
